### ISSUE TITLE
Review TOR for Metadata editor

### ISSUE THREAD

**Issue by thomas-maschler** [wri/gfw-sync#20]
(customize ArcCatalog metadata editor)

Earlier we already wrote some TDR to customize the metadata editor in ArcCatalog.
After our discussion yesterday we can go even further and add additional items for M&E to the metadata.

Thus-far, we forwarded TDR only to Blueraster, but maybe you know someone else you might want to do that job?

https://drive.google.com/file/d/0B7LnJyiFtqLeal8wcjBQbjBWdTg/view?usp=sharing

**Comment by sritchie** [comment]
Hey guys, a nice first task would probably be automating data transfer from S3 around our different data sources. This one is going to require getting up to speed on windows, ArcCatalog, just a ton of stuff. Let's get some of the basic ones done first, yeah? @eightysteele, thoughts?

**Comment by thomas-maschler** [comment]
Maybe we can have a quick chat what type of tasks will be a good for you to get started
I can also walk you through the tool architecture and explain how it works right now. We can then discuss if the current architecture makes sense of if we need to change it.

**Comment by eightysteele** [comment]
@sritchie yeah man, meeting with @thomas-maschler and @astrong19 now to figure out staging...

**Comment by sritchie** [comment]
Awesome - I’ll get the update from you afterward. I’m deep in some Clojure code now.

Sam Ritchie (@sritchie)
RaceHub Co-Founder
703.863.8561
www.racehubhq.com <http://www.racehubhq.com/>
Twitter <http://twitter.com/racehubhq> // Facebook <http://facebook.com/racehubhq>
