### ISSUE TITLE
Add M&E infos to metadata standard

### ISSUE THREAD

**Issue by thomas-maschler** [wri/gfw-sync#21]
Earlier we already created a metadata standard for our datasets.
We should add M&E related categories, too (as custom fields)

https://docs.google.com/spreadsheets/d/11nebe2AeQiQJDwWbe-QuS2FWr1Wxh_re7Z2JzRgzXYo/edit

**Comment by astrong19** [comment]
Yes, I'll meet with Katherine to decide on a few key metrics to add to our metadata standards.

**Comment by astrong19** [comment]
This is done.
