### ISSUE TITLE
Fix corrupted geometries for SAD-Imazon

### ISSUE THREAD

**Issue by thomas-maschler** [wri/gfw-sync#22]
Robin used this trick to fix it
https://github.com/wri/harvest-imazon/blob/master/harvest_imazon/normalize.py#L93-L122

When I ported the script into our tool, I thought I could handle this with 
```
arcpy.RepairGeometry_management
```
https://github.com/wri/gfw-sync/blob/master/imazon_sad.py#L213

but it doesn't seem to do anything. David is still reporting geometry errors

**Comment by thomas-maschler** [comment]
Ask David which exact Geometries are corrupt

**Comment by eightysteele** [comment]
@d4weed hey dude what imazon geoms are you seeing that are invalid?

**Comment by eightysteele** [comment]
@thomas-maschler @astrong19 we should find offending geoms and create a unit test for it.

**Comment by astrong19** [comment]
Here's what Robin was using: https://github.com/wri/harvest-imazon/blob/master/harvest_imazon/normalize.py#L93-L122
