### ISSUE TITLE
Date conversion field not working in umd_landsat_alerts.py

### ISSUE THREAD

**Issue by astrong19** [wri/gfw-sync#44]
We've had a number of issues getting the umd_landsat_alerts.py script to successfully convert the GRID_CODE julian values into a datetime field (M/D/Y). We've tried three different code spinets, and can't get any of them to execute in arcpy. 

Current error is: 

date field added
Traceback (most recent call last):
  File "umd_landsat_alerts.py", line 67, in <module>
    date = datetime.datetime(year, 1,1)+ datetime.timedelta(day-1)
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

**Comment by astrong19** [comment]
Also have tried this code: 

def getDate(day):
	Y=2015 
	if day < 32:
		M = 1 
		D = day
	elif day < 60:
		M = 2
		D = day - 31
	elif day < 91:
		M = 3
		D = day - 59
	elif day < 121:
		M = 4
		D = day - 90
	elif day < 152:
		M = 5
		D = day - 120
	elif day < 182:
		M = 6
		D = day - 151
	elif day < 213:
		M = 7
		D = day - 181
	elif day < 244:
		M = 8
		D = day - 212
	elif day < 274:
		M = 9
		D = day - 243
	elif day < 305:
		M = 10
		D = day - 273
	elif day < 335:
		M = 11
		D = day - 304
	elif day < 366:
		M = 12
		D = day - 334
	d =str(D) + "-" + str(M) + "-" + str(Y)
	return d

**Comment by astrong19** [comment]
And this 

def convert_julian(field_julian):
	d = datetime.strptime(field_julian, '%j')
	d.strftime("%Y/%m/%d") 
	newd = d.replace(year = 2015)
	print newd

**Comment by thomas-maschler** [comment]
This works for me

```Python
import datetime
d = datetime.datetime.strptime('2007300', '%Y%j')
d.strftime("%Y/%m/%d")
```

**Comment by astrong19** [comment]
Most of the solutions work in Field Calculator but stop working once placed in Arcpy, For example, using the code you suggested in arcpy (as shown below) won't convert the field. 

#create function 
def getDate(datefield):
	d = datetime.datetime.strptime('2007300', '%Y%j')
	d.strftime("%Y/%m/%d")
	return d

#execute calculate field 
merged_file = r"D:\temp\umd\points\gfw_landsat_alerts.shp"
expression = getDate("!GRID_CODE!")
field_name = "date"	
arcpy.CalculateField_management(merged_file, field_name, expression, "PYTHON_9.3")
print "dates converted"'''

**Comment by robinkraft** [comment]
Per [the confusing docs](http://resources.arcgis.com/EN/HELP/MAIN/10.2/index.html#//00170000004m000000), you need to write your python function and the expression using it as strings, and pass them into the CalculateField_management function. Something like the following should work:

```python
field_name = 'date'

codeblock = """def getDate(date_str):
    d = datetime.datetime.strptime(date_str, '%Y%j')
    return d.strftime('%Y/%m/%d')"""

expression = 'getDate(!GRID_CODE!)'

arcpy.CalculateField_management(inTable, field_name, expression, "PYTHON_9.3", codeblock)
```

**Comment by thomas-maschler** [comment]
Right,
Don’t forget the linebreaks in the codeblock

```Python

field_name = 'date'



codeblock = """def getDate(date_str):\n

    d = datetime.datetime.strptime(date_str, '%Y%j')\n

    return d.strftime('%Y/%m/%d')"""



expression = 'getDate(!GRID_CODE!)'



arcpy.CalculateField_management(inTable, field_name, expression, "PYTHON_9.3", codeblock)

```

**Comment by astrong19** [comment]
Great, thanks ya'll! Figured it out and committed the changes.
