### ISSUE TITLE
imazon_sad.py not updating dates

### ISSUE THREAD

**Issue by astrong19** [wri/gfw-sync#45]
The imazon_sad.py script is successfully grabbing the most recent data from the imazon website, however, it is not updating the dates for any data past 6/1/2015. The date field for 7/1/2015 and 8/1/2015 are left "null".

**Comment by thomas-maschler** [comment]
Did they change their data model?

**Comment by astrong19** [comment]
Doesn’t look like it:

http://www.imazongeo.org.br/doc/downloads.php
