### ISSUE TITLE
Metadata API breaks with latest Oauth2client version

### ISSUE THREAD

**Issue by thomas-maschler** [wri/gfw-sync#59]
`from oauth2client.client import SignedJwtAssertionCredentials`

doesn't work with latest (2.0) oauth2client version

you need to role back to an older version
`pip install oauth2client==1.5.2`

are there other ways to log in?

**Comment by mappingvermont** [comment]
Looks like it's possible:
http://gspread.readthedocs.org/en/latest/oauth2.html

Do you have 2.0 installed locally? The DM server is still using 1.5.2. Should I upgrade it?

**Comment by thomas-maschler** [comment]
I upgraded ArcGIS locally and had to reinstall all external modules. Then I noticed the broken dependency.

I wouldn't upgrade right away. There are more urgent issues to fix

.

**Comment by mappingvermont** [comment]
Great-- I'll update later this coming week.

**Comment by mappingvermont** [comment]
Updated to use OAuth 2.0. Should be all set.
